### PR TITLE
Correct RAM bounds so USB responses in all RAM get DMAed directly.

### PR DESCRIPTION
**Pull request by tannewt**

### CODE REVIEW

**Review by dhalbert — CHANGES_REQUESTED** [review]
The change of course is fine! Could you resubmit as a merge into branch `master-bugfixes`? `master` is meant to be the pristine "as downloaded" version, bugs and all.

Maybe I should change the name of the pristine branch to `downloaded` or `pristine` or something, since this is probably confusing. Let me know if you prefer that. I should enhance the update script to check that it's updating the right branch.

The dependency path is meant to be:
Atmel START -> `master` -> `master-bugfixes` -> `circuitpython`,
`circuitpython` contains our enhancements (not general bugfixes) solely for CPy.

**Comment by tannewt** [comment]
I changed the base. It should be good to go now.

**Comment by dhalbert** [comment]
✔️

**Comment by tannewt** [comment]
Do I need to do a second pull to merge this fix into the `circuitpython` branch and then update the submodule in circuitpython?

**Comment by dhalbert** [comment]
Go ahead and just do it with a push to circuitpython. The change has been reviewed, and GitHub is not automating a manual two-step process. If we could do it in one step we would.

**Pull request merged**
