### PR TITLE
Master bugfixes

### PR DESCRIPTION
**Pull request by dhalbert**
Propagating usart_update down to master_bugfixes.

### CODE REVIEW

**Comment by dhalbert** [comment]
@tannewt OK sorry, let me start over with a sort-of review request. Could you take a look at certain  diffs in this already-merged PR? It's not that the diff's need review in this branch, but I need to merge this into the asf4 circuitpython branch and the code changes here may affect your changes in that branch. I did an initial merge, there were conflicts, and it was not at all obvious what to do to fix. It's possible these changes subsume some of yours.

Could you take a look at these and consider how they might affect your changes? Thanks.

samd{21,51}/usb/class/msc/device/mscdf.c
and
samd{21,51}/usb/device/usbdc.c

**Comment by dhalbert** [comment]
Here are URLs for the diffs. These are the diffs between the previous asf4 version and the new one, not between theirs and yours.

Could you take a look at these diffs and consider how they might affect your changes? Thanks.

samd{21,51}/usb/class/msc/device/mscdf.c
https://github.com/adafruit/asf4/pull/17/files#diff-38c0d807bb479d12831309356b646c1e
https://github.com/adafruit/asf4/pull/17/files#diff-fd4a56e25e4113c09254bd04d9f573f9

and
samd{21,51}/usb/device/usbdc.c
https://github.com/adafruit/asf4/pull/17/files#diff-7d7b198cecdf5f855417b7eaaa21f859
https://github.com/adafruit/asf4/pull/17/files#diff-3d7251f1e2b46e7de26f0c7a200c27d9

**Comment by tannewt** [comment]
This is what we went over on Discord right? Need me to look still?

**Comment by dhalbert** [comment]
That was it. I still need to do the merge. Got sidetracked with a lot of other stuff.

**Comment by dhalbert** [comment]
I mean I still need to do the merge to circuitpython (which will be another PR).

**Comment by tannewt** [comment]
Ok, works for me.

**Pull request merged**
